- name: Delete Linode
  hosts: localhost
  vars_files:
    - ./group_vars/example_group/vars
  tasks:
  - name: Delete your Linode Instance.
    linode_v4:
      label: "{{ label }}"
      access_token: "{{ token }}"
      state: absent

